# Generated by Django 5.1.3 on 2025-01-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('natinality', models.CharField(choices=[('AF', 'Afegão'), ('AL', 'Albanês'), ('DZ', 'Argelino'), ('AR', 'Argentino'), ('AU', 'Australiano'), ('BR', 'Brasileiro'), ('CA', 'Canadense'), ('CN', 'Chinês'), ('FR', 'Francês'), ('DE', 'Alemão'), ('IN', 'Indiano'), ('IT', 'Italiano'), ('JP', 'Japonês'), ('MX', 'Mexicano'), ('RU', 'Russo'), ('ZA', 'Sul-africano'), ('ES', 'Espanhol'), ('SE', 'Sueco'), ('CH', 'Suíço'), ('US', 'Americano')], max_length=100)),
            ],
        ),
    ]
